package ro.ubbcluj.map.socialnetworkfx.utility;

/**
 * Identifiers for the Popup alerts.
 */
public enum PopupEnum {
    EMPTY_TABLE_EXCEPTION,
    EMPTY_LIST_EXCEPTION,
    NONE_SELECTED_EXCEPTION,
    REMOVE_USER_EXCEPTION,
    REMOVE_USER_SUCCESS,
    ADD_USER_EXCEPTION,
    ADD_USER_SUCCESS,
    UPDATE_USER_EXCEPTION,
    UPDATE_USER_SUCCESS,
    ADD_FRIENDSHIP_EXCEPTION,
    ADD_FRIENDSHIP_SUCCESS,
    REMOVE_FRIENDSHIP_EXCEPTION,
    REMOVE_FRIENDSHIP_SUCCESS,
    FRIENDSHIP_REQUEST_EXCEPTION,
    FRIENDSHIP_REQUEST_SUCCESS,
}
